### ISSUE TITLE
Knowledge Graph Dataset Todo List

### ISSUE THREAD

**Issue by xingjian-zhang** [Graph-Learning-Benchmarks/gli#200]
- [x] Rename `type` attribute (#192).
- [x] Add `num_relations` attribute in `KGRelationPrediction` (#189).
- [x] Reindex node ids (#190)
EDIT:
- [x] Add `target` attribute in `KGRelationPrediction` (#189)

@jupiterepoch - Could you please have a look at these issues when available?
